### ISSUE TITLE
AssertionError: Can not find executable file

### ISSUE THREAD

**Issue by sunshineywz123** [Totoro97/f2-nerf#10]
python scripts/run.py --config-name=wanjinyou dataset_name=example case_name=ngp_fox mode=render_path is_continue=true
Error executing job with overrides: ['dataset_name=example', 'case_name=ngp_fox', 'mode=render_path', 'is_continue=true']
Traceback (most recent call last):
  File "scripts/run.py", line 74, in main
    assert False, 'Can not find executable file'
AssertionError: Can not find executable file

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by Totoro97** [comment]
Hi, it seems in `scripts/run.py`, Hydra automatically changes the working directory. I have updated `run.py` to override the working directory. You can try the latest version and run command `python scripts/run.py --config-name=wanjinyou dataset_name=example case_name=ngp_fox mode=train +work_dir=$(pwd)`.

**Comment by adilyoltay** [comment]
did you update run.py ?

**Comment by mmacasang1014** [comment]
did someone manage to solve this? would really appreciate the help.

My environment:
Windows 10
Nvidia RTX 2080 GPU

**Comment by yuedumingz** [comment]
python scripts/run.py --config-name=wanjinyou dataset_name=example case_name=ngp_fox mode=train +work_dir=$(pwd)
Working directory is /DATA/zbz/new-project/f2-nerf
Error executing job with overrides: ['dataset_name=example', 'case_name=ngp_fox', 'mode=train', '+work_dir=/DATA/zbz/new-project/f2-nerf']
Traceback (most recent call last):
  File "scripts/run.py", line 78, in main
    assert False, 'Can not find executable file'
AssertionError: Can not find executable file

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

I also meet this error，although use the upgraded file and command
